stages:
  - check

check-bash:
  stage: check
  tags:
    - linux
    - shellcheck
  script:
    # NOTE: These errors are excluded:
    # SC2185: Some finds don't have a default path. Specify '.' explicitly. (find -name "*.txt" for example would trigger this)
    - shellcheck --exclude=SC2185 $(find -name "*.sh")

check-json:
  stage: check
  image: node:latest
  script:
    # https://stackoverflow.com/a/43318794
    # Install ESLint in this docker container
    - npm install -g eslint
    # For the eslint.config.mjs configuration file
    - npm install @eslint/js eslint-plugin-jsonc -D
    # Run ESLint
    - ESLINT_USE_FLAT_CONFIG=true eslint --config eslint.config.mjs .
